FROM python:3.9-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libgl1 \
    libglib2.0-0 \
    libgl1-mesa-glx   # Install OpenGL libraries

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY vector_database /app/vector_database
COPY model_client.py .
COPY config.py .

# Set PYTHONPATH to include the /app directory
ENV PYTHONPATH="/app"

EXPOSE 8006

# Define the command to run the application
CMD ["python", "model_client.py"]
