FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libgl1 \
    libglib2.0-0 \
    libgl1-mesa-glx   # Install OpenGL libraries

WORKDIR /app

COPY requirements.txt .
COPY avito_df_final.csv .

RUN pip install --no-cache-dir -r requirements.txt

COPY vector_database /app/vector_database
COPY model_client.py .
COPY config.py .

ENV PYTHONPATH="/app"

EXPOSE 8006

CMD ["python", "model_client.py"]
