FROM python:3.9-slim

WORKDIR /app


COPY config.py /app/

COPY vector_database/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY vector_database /app/vector_database

ENV PYTHONPATH="/app"

CMD ["python", "vector_database/vector_client.py"]
