FROM python:3.9-slim

WORKDIR /app

COPY config.py /app/

COPY rxconfig.py /app/

COPY smart_cam/requirements.txt .

# Install necessary system packages for building Python extensions
RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    unzip \
    curl \
 && rm -rf /var/lib/apt/lists/*

RUN curl -L --fail --show-error --silent --output bun.zip "https://github.com/oven-sh/bun/releases/download/bun-v1.1.3/bun-linux-aarch64.zip" && \
    unzip bun.zip -d /usr/local/bin && \
    rm bun.zip

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY smart_cam /app/smart_cam

ENV PYTHONPATH="/app"

EXPOSE 3000
EXPOSE 8000

CMD ["python", "-m", "reflex", "run"]
